### PR TITLE
Add support for LLVM 11

### PR DESCRIPTION
**Pull request by ghaith**
## Description
Added support for an LLVM 11 future.
Updated the debug builder API to support the new parameters
Fixed some failing tests
Updated travis config 

## Related Issue
#217 

## How This Has Been Tested
Ran tests for the older features and the new feature
Did not add new tests as no new functionality was added
**2 Tests are still failing on my machine**, one for enums and one for alignment.

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ghaith** [comment]
I created this as a draft since 2 tests still fail.
One test deals with alignment values `test_instruction_values::test_mem_instructions` , where we were expecting them to be 0, but they are 4 in LLVM11, I did not find any reference to this change here: https://releases.llvm.org/11.0.0/docs/ReleaseNotes.html which is why i did not yet fix the test.
The other test has to do with the enum values for metadata `test_attributes::test_enum_attribute_kinds`. The [LLVM Documentation](https://llvm.org/doxygen/group__LLVMCCoreContext.html#ga4bd62e3a1b94b92e32d892c8f89dea1c) says these values are not maintained in the C API and can change at any time. So I'm not sure how we can test them reliably or why we should.

**Comment by TheDan64** [comment]
If you see enum attribute kind numbers that changed, you can remove just the ones that are no longer the same and keep the working ones

**Comment by ghaith** [comment]
> If you see enum attribute kind numbers that changed, you can remove just the ones that are no longer the same and keep the working ones

all tested attributes changed, the test only has the non-existing attributes now.

**Comment by ghaith** [comment]
I pushed the updated tests, but I'm still having some issues in the build.
If I run all tests (using cargo test) then the test crash with : 
`Caused by:
  process didn't exit successfully: `/usr/local/src/target/debug/deps/all-4bbc9f42c9e86587` (signal: 11, SIGSEGV: invalid memory reference)
`
If I run individual tests they are fine.

I'm also not happy with all the #[cfg(feature...] I had to introduce since they need to be updated again with each new llvm version. Do you have suggestions for that? Should I just duplicate the methods and use llvm_version? Or do you know if llvm_version is usable inside parameter lists? I haven't worked much with features in rust.

**Comment by ghaith** [comment]
I found the issue with the segfault, it was due to a missing feature flag in the test_globals section.
I also updated the travis setup.
I'll set the PR as ready from my side, tell me if I should do more cleanups there.

**Comment by TheDan64** [comment]
Sorry for the delay, been mostly AFK for the holidays. Should be able to take a look soon

**Comment by TheDan64** [comment]
> newer symver versions no longer compile with rust 1.42

What does this mean exactly??

File: src/debug_info.rs [hunk 1]
```diff
@@ -210,6 +211,59 @@ impl<'ctx> DebugInfoBuilder<'ctx> {
...
+        is_optimized: bool,
+        flags: &str,
+        runtime_ver: libc::c_uint,
+        split_name: &str,
+        kind: DWARFEmissionKind,
+        dwo_id: libc::c_uint,
+        split_debug_inlining: bool,
+        debug_info_for_profiling: bool,
+        sysroot: &str,
+        sdk: &str,
```
Comment (TheDan64) [inline src/debug_info.rs:231]: Rather than duplicating these functions we should just add `llvm_version` to the params

File: src/types/enums.rs [hunk 2]
```diff
@@ -103,13 +103,17 @@ impl<'ctx> AnyTypeEnum<'ctx> {
             LLVMTypeKind::LLVMX86_FP80TypeKind |
             LLVMTypeKind::LLVMFP128TypeKind |
             LLVMTypeKind::LLVMPPC_FP128TypeKind => AnyTypeEnum::FloatType(FloatType::new(type_)),
+            #[cfg(feature = "llvm11-0")]
+            LLVMTypeKind::LLVMBFloatTypeKind => AnyTypeEnum::FloatType(FloatType::new(type_)),
```
Comment (TheDan64) [inline src/types/enums.rs:107]: Any idea what this new type is for?

File: src/values/instruction_value.rs [hunk 3]
```diff
@@ -277,6 +278,22 @@ impl<'ctx> InstructionValue<'ctx> {
         }
         Ok(unsafe { LLVMSetAlignment(self.as_value_ref(), alignment) })
     }
+    
+    // SubTypes: Only apply to memory access and alloca instructions
+    /// Sets alignment on a memory access instruction or alloca.
+    #[llvm_versions(11.0..=latest)]
```
Comment (TheDan64) [inline src/values/instruction_value.rs:284]: Why was this function split out?

**Review by TheDan64 — COMMENTED** [review]
Looks pretty good overall but have some thoughts. Also really confused about the version change.

**Comment by ghaith** [comment]
> > newer symver versions no longer compile with rust 1.42
> 
> What does this mean exactly?? I don't see any reason to have to update to a newer rust?

The newest semver-parser package at the time, on which llvm-sys depends did not build with rust versions < 1.49.0, this is due to them using a non build-in inner attribute, they seem to have that fixed in 0.10.2 so i will revert this back

```
 Compiling semver-parser v0.10.1
error[E0658]: non-builtin inner attributes are unstable
 --> /home/ghaith/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
  |
4 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726


```

File: src/values/instruction_value.rs (hunk 3 above)
Comment (ghaith) [reply src/values/instruction_value.rs:284]: LLVM11 introduced some alignment guards, I thought we should not force <11 to use them, but I will move this to a feature check in the same function

File: src/types/enums.rs (hunk 2 above)
Comment (ghaith) [reply src/types/enums.rs:107]: BFloat : https://releases.llvm.org/11.0.0/docs/ReleaseNotes.html#changes-to-the-aarch64-backend
Looks like an Aarch64 (64 bit ARM) specific field

The scalable vector looks like a new generic IR type: https://releases.llvm.org/11.0.0/docs/ReleaseNotes.html#changes-to-the-llvm-ir

File: src/debug_info.rs (hunk 1 above)
Comment (ghaith) [reply src/debug_info.rs:231]: I had to use #[cfg(feature(..)] since custom attributes don't work on parameters.
I also still have to duplicate the function call since attributes on parameter calls are also experimental

**Comment by TheDan64** [comment]
Ohh, thanks for clarifying!

File: src/values/instruction_value.rs (hunk 3 above)
Comment (TheDan64) [reply src/values/instruction_value.rs]: So older versions allowed alignment 0 but 11 no longer does?

Comment (ghaith) [reply src/values/instruction_value.rs]: I could not find it in the release notes, so I looked for changes in the code and there has been some work on alignments.
Mainly _most_ of the `setAlignment` methods in [`llvm/IR/Core.cpp`](https://github.com/llvm/llvm-project/blob/release/11.x/llvm/lib/IR/Core.cpp) will now call `Align()` instead of `MaybeAlign()` which fails on 0 values. The only exception is `GlobalValue`. 
I can change this back to remove the check but it means setting alignment to 0 will panic instead of returning the Result<>. 
Since this is on instruction_value and instruction will check for 0, it might be worth keeping the check there.
The changes on LLVM for that are : 
https://reviews.llvm.org/D77454
https://reviews.llvm.org/D79968
https://reviews.llvm.org/D80044

Comment (TheDan64) [reply src/values/instruction_value.rs]: Great catch. We should just add a feature check in the same function I think? Unless you feel strongly otherwise

Comment (TheDan64) [reply src/values/instruction_value.rs]: We really don't want LLVM to hit an assertion under us because that's bad news

**Review by TheDan64 — APPROVED** [review]
Looks good. Left a comment on the alignment comment thread. If it's all set then we can merge

File: src/values/instruction_value.rs (hunk 3 above)
Comment (ghaith) [reply src/values/instruction_value.rs]: I already changed it to a feature check in a previous commit : https://github.com/TheDan64/inkwell/pull/224/files#diff-8e2e5aa572ea6e78c6571db5bae3c54a30f55b202b9c0995d76e145013ea96c1

**Comment by TheDan64** [comment]
Thanks! Sorry it took so long.
